resources:
- statefulset.yml
- service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: main-db-env
  literals:
    - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    - POSTGRES_USER=workshop
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:4317


secretGenerator:
- name: main-db-secrets
  envs:
  - .main-db.secrets
